/* Auto-generated by genmsg_cpp for file /usr0/home/venkatrn/groovy_workspace/sandbox/ltm_stack/ltm_msgs/msg/DModel.msg */
#ifndef LTM_MSGS_MESSAGE_DMODEL_H
#define LTM_MSGS_MESSAGE_DMODEL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseArray.h"
#include "ltm_msgs/Edge.h"

namespace ltm_msgs
{
template <class ContainerAllocator>
struct DModel_ {
  typedef DModel_<ContainerAllocator> Type;

  DModel_()
  : points()
  , edges()
  {
  }

  DModel_(const ContainerAllocator& _alloc)
  : points(_alloc)
  , edges(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _points_type;
   ::geometry_msgs::PoseArray_<ContainerAllocator>  points;

  typedef std::vector< ::ltm_msgs::Edge_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ltm_msgs::Edge_<ContainerAllocator> >::other >  _edges_type;
  std::vector< ::ltm_msgs::Edge_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ltm_msgs::Edge_<ContainerAllocator> >::other >  edges;


  typedef boost::shared_ptr< ::ltm_msgs::DModel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ltm_msgs::DModel_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DModel
typedef  ::ltm_msgs::DModel_<std::allocator<void> > DModel;

typedef boost::shared_ptr< ::ltm_msgs::DModel> DModelPtr;
typedef boost::shared_ptr< ::ltm_msgs::DModel const> DModelConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ltm_msgs::DModel_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ltm_msgs::DModel_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ltm_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ltm_msgs::DModel_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ltm_msgs::DModel_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ltm_msgs::DModel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "50a566339aa89b9aa728558673bc6645";
  }

  static const char* value(const  ::ltm_msgs::DModel_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x50a566339aa89b9aULL;
  static const uint64_t static_value2 = 0xa728558673bc6645ULL;
};

template<class ContainerAllocator>
struct DataType< ::ltm_msgs::DModel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ltm_msgs/DModel";
  }

  static const char* value(const  ::ltm_msgs::DModel_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ltm_msgs::DModel_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PoseArray points\n\
ltm_msgs/Edge[] edges\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: ltm_msgs/Edge\n\
int64[2] nodes\n\
int64 joint_type\n\
float64[3] normal\n\
float64 radius\n\
\n\
";
  }

  static const char* value(const  ::ltm_msgs::DModel_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ltm_msgs::DModel_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.points);
    stream.next(m.edges);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DModel_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ltm_msgs::DModel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ltm_msgs::DModel_<ContainerAllocator> & v) 
  {
    s << indent << "points: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.points);
    s << indent << "edges[]" << std::endl;
    for (size_t i = 0; i < v.edges.size(); ++i)
    {
      s << indent << "  edges[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ltm_msgs::Edge_<ContainerAllocator> >::stream(s, indent + "    ", v.edges[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // LTM_MSGS_MESSAGE_DMODEL_H

